import type { Metadata } from "next";
import "../styles/globals.css";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"



export const metadata: Metadata = {
  title: "Agency Cameroon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#09090B]">
      <body className={cn(
          "min-h-screen overflow-x-hidden",
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
          </ThemeProvider>
          </body>
    </html>
  );
}
